import type { ToolManifest } from '@flowstate/core';

/**
 * Seed data for the tool directory while we build out the registry layer.
 * Real manifests will be loaded from .agent/tools/**.
 */
export const FIXTURE_TOOLS: ToolManifest[] = [
  {
    id: 'gmail',
    name: 'Gmail',
    kind: 'mcp',
    icon: 'gmail',
    brandColor: '#EA4335',
    description: 'Send, read, search, and label email through your Gmail account.',
    capabilities: [
      'communication.email.send',
      'communication.email.read',
      'communication.email.search',
      'communication.email.label',
    ],
    tags: ['email', 'google', 'communication'],
    publisher: 'official',
    version: '1.2.0',
    auth: { kind: 'oauth2', scopes: ['gmail.send', 'gmail.readonly'] },
    authStatus: 'ready',
    provider: { command: 'npx', args: ['-y', '@flowstate/mcp-gmail'] },
    actions: [
      { id: 'send', summary: 'Send an email' },
      { id: 'search', summary: 'Search inbox' },
      { id: 'label.add', summary: 'Add a label' },
    ],
    ui: { category: 'Communication' },
  },
  {
    id: 'gcloud',
    name: 'Google Cloud',
    kind: 'cli',
    icon: 'gcloud',
    brandColor: '#4285F4',
    description: 'Manage all of Google Cloud through the gcloud CLI — Run, Storage, IAM, BigQuery.',
    capabilities: [
      'cloud.gcp.deploy',
      'cloud.gcp.storage',
      'cloud.gcp.iam',
      'cloud.gcp.bigquery',
    ],
    tags: ['cloud', 'gcp', 'devops'],
    publisher: 'official',
    auth: { kind: 'ambient', statusCheck: 'gcloud auth list' },
    authStatus: 'ready',
    provider: { command: 'gcloud' },
    actions: [
      { id: 'run.deploy', summary: 'Deploy to Cloud Run' },
      { id: 'storage.list', summary: 'List buckets' },
      { id: 'iam.policy.get', summary: 'Get IAM policy' },
    ],
    ui: { category: 'Cloud' },
  },
  {
    id: 'github',
    name: 'GitHub',
    kind: 'cli',
    icon: 'github',
    brandColor: '#181717',
    description: 'Create PRs, manage issues, run workflows. Uses your gh CLI auth.',
    capabilities: ['code.repo.read', 'code.pr.create', 'code.issue.create', 'code.workflow.run'],
    tags: ['code', 'git', 'github'],
    publisher: 'official',
    auth: { kind: 'ambient', statusCheck: 'gh auth status' },
    authStatus: 'ready',
    provider: { command: 'gh' },
    actions: [
      { id: 'pr.create', summary: 'Open a pull request' },
      { id: 'issue.list', summary: 'List issues' },
    ],
    ui: { category: 'Code' },
  },
  {
    id: 'stripe',
    name: 'Stripe',
    kind: 'mcp',
    icon: 'stripe',
    brandColor: '#635BFF',
    description: 'Charges, refunds, customers, subscriptions. Read-write API surface.',
    capabilities: [
      'payment.charge.create',
      'payment.refund.create',
      'payment.subscription.cancel',
    ],
    tags: ['payments', 'stripe'],
    publisher: 'official',
    auth: { kind: 'api_key', required: ['STRIPE_API_KEY'] },
    authStatus: 'ready',
    provider: { command: 'npx', args: ['-y', '@stripe/mcp'] },
    actions: [
      { id: 'refunds.create', summary: 'Issue a refund' },
      { id: 'customers.retrieve', summary: 'Get a customer' },
    ],
    ui: { category: 'Payments' },
  },
  {
    id: 'slack',
    name: 'Slack',
    kind: 'composio',
    icon: 'slack',
    brandColor: '#4A154B',
    description: 'Post messages, open channels, react. Comes with Composio-managed OAuth.',
    capabilities: ['communication.chat.post', 'communication.chat.dm'],
    tags: ['chat', 'slack', 'communication'],
    publisher: 'community',
    auth: { kind: 'oauth2' },
    authStatus: 'needs_setup',
    provider: { action: 'SLACK_SEND_MESSAGE' },
    actions: [{ id: 'post', summary: 'Post a message' }],
    ui: { category: 'Communication' },
  },
  {
    id: 'notion',
    name: 'Notion',
    kind: 'http',
    icon: 'notion',
    brandColor: '#000000',
    description: 'Create pages, append blocks, query databases. Direct REST API.',
    capabilities: ['note.page.create', 'note.database.query'],
    tags: ['notes', 'docs', 'notion'],
    publisher: 'official',
    auth: { kind: 'api_key', required: ['NOTION_TOKEN'] },
    authStatus: 'ready',
    provider: { baseUrl: 'https://api.notion.com/v1' },
    actions: [
      { id: 'pages.create', summary: 'Create a page' },
      { id: 'db.query', summary: 'Query a database' },
    ],
    ui: { category: 'Productivity' },
  },
  {
    id: 'kubectl',
    name: 'Kubernetes',
    kind: 'cli',
    icon: 'k8s',
    brandColor: '#326CE5',
    description: 'Inspect and operate Kubernetes clusters via kubectl. Read-only by default.',
    capabilities: ['cloud.k8s.read', 'cloud.k8s.exec'],
    tags: ['k8s', 'devops', 'infra'],
    publisher: 'official',
    auth: { kind: 'ambient', statusCheck: 'kubectl config current-context' },
    authStatus: 'expired',
    provider: { command: 'kubectl' },
    actions: [
      { id: 'get.pods', summary: 'List pods' },
      { id: 'logs', summary: 'Stream logs' },
    ],
    ui: { category: 'Cloud' },
  },
  {
    id: 'onboard-customer',
    name: 'Onboard customer',
    kind: 'skill',
    icon: 'skill',
    brandColor: '#FF5733',
    description:
      'A reusable skill — verify identity, provision workspace, send welcome series. Calls Stripe + Gmail + Notion under the hood.',
    capabilities: ['workflow.customer.onboard'],
    tags: ['skill', 'workflow', 'crm'],
    publisher: 'custom',
    auth: { kind: 'none' },
    authStatus: 'ready',
    provider: { path: './skills/onboard-customer.md' },
    actions: [{ id: 'run', summary: 'Onboard a new customer' }],
    ui: { category: 'Workflows' },
  },
  {
    id: 'fs',
    name: 'Filesystem',
    kind: 'shell',
    icon: 'fs',
    description: 'Read, write, and search files in the current workspace. Sandboxed.',
    capabilities: ['file.read', 'file.write', 'file.search'],
    tags: ['files', 'local'],
    publisher: 'official',
    auth: { kind: 'none' },
    authStatus: 'ready',
    provider: { sandboxed: true, root: './' },
    actions: [
      { id: 'read', summary: 'Read a file' },
      { id: 'write', summary: 'Write a file' },
    ],
    ui: { category: 'Local' },
  },
  {
    id: 'linear',
    name: 'Linear',
    kind: 'mcp',
    icon: 'linear',
    brandColor: '#5E6AD2',
    description: 'Issues, projects, cycles. Built for engineering velocity.',
    capabilities: ['code.issue.create', 'project.cycle.read'],
    tags: ['issues', 'product'],
    publisher: 'community',
    auth: { kind: 'api_key', required: ['LINEAR_API_KEY'] },
    authStatus: 'ready',
    provider: { command: 'linear-mcp' },
    actions: [
      { id: 'issue.create', summary: 'Create an issue' },
      { id: 'cycle.current', summary: 'Get current cycle' },
    ],
    ui: { category: 'Productivity' },
  },
  {
    id: 'browser',
    name: 'Browser',
    kind: 'shell',
    icon: 'browser',
    description: 'Headless browser via Playwright — for sites without an API.',
    capabilities: ['web.browse', 'web.scrape', 'web.fill_form'],
    tags: ['browser', 'web', 'scrape'],
    publisher: 'official',
    auth: { kind: 'none' },
    authStatus: 'ready',
    provider: { engine: 'playwright' },
    actions: [
      { id: 'visit', summary: 'Visit a URL' },
      { id: 'extract', summary: 'Extract content' },
    ],
    ui: { category: 'Web' },
  },
  {
    id: 'postgres',
    name: 'Postgres',
    kind: 'mcp',
    icon: 'postgres',
    brandColor: '#336791',
    description: 'Run SQL against any Postgres database. Read-only by default.',
    capabilities: ['data.query.sql', 'data.schema.inspect'],
    tags: ['data', 'sql', 'postgres'],
    publisher: 'official',
    auth: { kind: 'api_key', required: ['POSTGRES_URL'] },
    authStatus: 'ready',
    provider: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-postgres'] },
    actions: [
      { id: 'query', summary: 'Run a SQL query' },
      { id: 'schema', summary: 'Inspect schema' },
    ],
    ui: { category: 'Data' },
  },
];
